version: '3.3'
services:
      tensorflowapi:
        container_name: 'tensorflowapi'
        build: './api'
        ports:
            - '8080:8080'
        volumes:
            - './api:./go/src/app'