version: '3.3'
services:
    tensorflowAPI:
        container_name: 'tensorflowAPI'
        build: '.'
        ports:
            - '8080:8080'
        volumes:
            - '.:../golangTensorflowAPI'